# Generated by Django 4.2 on 2026-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_machinearcade_id_alter_maintenance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='date_reparation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machinearcade',
            name='etat',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_PANNE', 'En Panne'), ('EN_MAINTENANCE', 'En Maintenance'), ('HORS_SERVICE', 'Hors Service')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='etat',
            field=models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20),
        ),
        migrations.AlterField(
            model_name='panne',
            name='statut',
            field=models.CharField(choices=[('SIGNALEE', 'Signalée'), ('EN_COURS', 'En cours de traitement'), ('REPAREE', 'Réparée')], default='SIGNALEE', max_length=20),
        ),
    ]
