# Generated by Django 4.2 on 2026-01-23 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_maintenance_description_panne_date_reparation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Maintenance', 'verbose_name_plural': 'Maintenances'},
        ),
        migrations.AlterModelOptions(
            name='panne',
            options={'ordering': ['-date_declaration'], 'verbose_name': 'Panne', 'verbose_name_plural': 'Pannes'},
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='date_installation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='derniere_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
        migrations.AddField(
            model_name='machinearcade',
            name='prochaine_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_debut_reelle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_fin_reelle',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='pieces_utilisees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='rapport',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_rapports/'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_maintenance',
            field=models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective'), ('PREDICTIVE', 'Prédictive')], default='PREVENTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='panne',
            name='commentaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='cout_reparation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='duree_reparation',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='pieces_remplacees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='priorite',
            field=models.CharField(choices=[('HAUTE', 'Haute'), ('MOYENNE', 'Moyenne'), ('BASSE', 'Basse'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=20),
        ),
        migrations.AddField(
            model_name='panne',
            name='technicien_assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIEN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pannes_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='panne',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes_signalees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TECHNICIEN', 'Technicien'), ('INVITE', 'Invité')], default='INVITE', max_length=20),
        ),
    ]
